apiVersion: v1
kind: Service

metadata: 
  name: mybackend-service
spec:
  type: NodePort
  ports: 
    - targetPort: 5005
      port: 5005
      nodePort: 30006

  selector:
    app: my-backend
    type: backend